Repository elastic/oblt-actions, pull requests merged in 2024-05, with the labels that each got.

#1 Add pre-commit
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
Labels: changelog:chore

#2 Add release flow workflows
  .github/release-drafter.yml
  .github/workflows/create-major-tag.yml
  .github/workflows/release-drafter.yml
  .github/workflows/required-labels.yml
  README.md
  docs/RELEASE.md
Labels: changelog:ci

#3 Add google/auth action
  .github/workflows/test-google-auth.yml
  google/auth/README.md
  google/auth/action.yml
Labels: changelog:feature

#4 feat: add updatecli and slack GitHub composite actions
  .github/workflows/test-updatecli-run.yml
  slack/send/README.md
  slack/send/action.yml
  updatecli/install/README.md
  updatecli/install/action.yml
  updatecli/run-and-notify/README.md
  updatecli/run-and-notify/action.yml
  updatecli/run/README.md
  updatecli/run/action.yml
Labels: changelog:enhancement

#7 fix: typo in the inputs
  updatecli/run-and-notify/README.md
  updatecli/run-and-notify/action.yml
Labels: changelog:fix

#6 Add git/setup action
  .github/workflows/test-git-setup.yml
  .github/workflows/test-google-auth.yml
  git/setup/README.md
  git/setup/action.yml
Labels: changelog:feature

#9 Add test check if no action source code is touched
  .github/workflows/no-test.yml
Labels: changelog:ci

#8 Release v1.0.0 without breaking changes
  README.md
Labels: changelog:breaking

#5 Add oblt-cli/setup action
  .github/workflows/test-oblt-cli-setup.yml
  oblt-cli/setup/README.md
  oblt-cli/setup/action.yml
  oblt-cli/setup/download.sh
Labels: changelog:feature

#11 Add oblt-cli/cluster-name-validation action
  .github/workflows/no-test.yml
  .github/workflows/test-oblt-cli-cluster-name-validation-cluster-info-file.yml
  .github/workflows/test-oblt-cli-cluster-name-validation-cluster-name.yml
  .github/workflows/test-oblt-cli-cluster-name-validation-failures.yml
  oblt-cli/cluster-name-validation/README.md
  oblt-cli/cluster-name-validation/action.yml
Labels: changelog:feature

#10 Add oblt-cli/cluster-credentials action
  .github/workflows/no-test.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
  oblt-cli/cluster-credentials/README.md
  oblt-cli/cluster-credentials/action.yml
Labels: changelog:feature

#12 Add oblt-cli/run action
  .github/workflows/no-test.yml
  .github/workflows/test-oblt-cli-run.yml
  oblt-cli/run/README.md
  oblt-cli/run/action.yml
Labels: changelog:feature

#15 feat(buildkite): support buildkite run with wait-for
  .github/workflows/no-test.yml
  .github/workflows/test-buildkite-run.yml
  buildkite/run/README.md
  buildkite/run/action.yml
  buildkite/run/run.sh
  buildkite/run/wait-for.sh
Labels: changelog:feature
