Repository elastic/oblt-actions, pull requests merged in 2024-07, with the labels that each got.

#74 Use dependabot wildcard directories
  .github/dependabot.yml
Labels: changelog:chore

#73 oblt-cli/setup: `version` input precedence
  .github/workflows/test-oblt-cli-setup.yml
  oblt-cli/setup/.default-oblt-cli-version
  oblt-cli/setup/README.md
  oblt-cli/setup/action.yml
  oblt-cli/setup/download.sh
Labels: changelog:enhancement

#75 oblt-cli/setup: Add note why you cannot automatically use the latest oblt-cli version
  oblt-cli/setup/README.md
Labels: changelog:docs

#76 oblt-cli/setup: bump oblt-cli version 7.3.1
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies

#77 aws/auth: Add `role-duration-seconds` input
  aws/auth/README.md
  aws/auth/action.yml
Labels: changelog:feature

#79 Revert "fix(google/auth): honour the project-id input"
  google/auth/action.yml
Labels: changelog:fix

#80 google/auth: Add `project-id` input
  google/auth/README.md
  google/auth/action.yml
Labels: changelog:feature

#78 chore: bump oblt setup version
  oblt-cli/run/action.yml
Labels: changelog:dependencies

#83 Setup updatecli for oblt-cli version
  .ci/updatecli/values.d/oblt-cli.yml
  .ci/updatecli/values.d/scm.yml
  .ci/updatecli/values.d/update-compose.yml
  .github/workflows/updatecli.yml
  update-compose.yaml
Labels: changelog:chore

#85 Update oblt-cli/version updatecli policy
  .ci/updatecli/values.d/oblt-cli.yml
  .ci/updatecli/values.d/scm.yml
Labels: changelog:chore

#88 deps(updatecli): bump all policies
  update-compose.yaml
Labels: changelog:dependencies

#90 deps(updatecli): bump all policies
  update-compose.yaml
Labels: changelog:dependencies

#91 deps: Bump oblt-cli version to 7.5.1
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies

#92 deps(updatecli): bump all policies
  update-compose.yaml
Labels: changelog:dependencies

#99 deps: Bump oblt-cli version to 7.5.5
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies

#100 deps: Bump oblt-cli version to 7.5.12
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies
