Repository elastic/oblt-actions, pull requests merged in 2024-09, with the labels that each got.

#109 feat: support active branches
  .github/workflows/test-elastic-active-branches.yml
  elastic/active-branches/README.md
  elastic/active-branches/action.yml
  elastic/active-branches/script.py
Labels: changelog:feature

#110 deps: Bump oblt-cli version to 7.5.20
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies

#111 deps(updatecli): bump all policies
  .ci/updatecli/values.d/scm.yml
  updatecli-compose.yaml
Labels: changelog:skip

#114 Add `test-report` action
  test-report/README.md
  test-report/action.yml
Labels: changelog:feature

#118 feat(await-maven-artifact): migrate from https://github.com/elastic/apm-pipeline-library
  .github/workflows/test-maven-await-artifact.yml
  maven/await-artifact/README.md
  maven/await-artifact/action.yml
Labels: changelog:feature

#120 feat(github): validate-comment
  github/validate-comment/README.md
  github/validate-comment/action.yml
Labels: changelog:feature

#113 github-action: use ephemeral tokens with the required permissions
  .github/workflows/updatecli.yml
Labels: changelog:dependencies

#121 deps: Bump oblt-cli version to 7.5.21
  oblt-cli/setup/.default-oblt-cli-version
Labels: changelog:dependencies

#122 deps(updatecli): bump all policies
  updatecli-compose.yaml
Labels: changelog:dependencies

#129 ci: use GitHub app for ephemeral tokens
  .github/workflows/test-oblt-cli-cluster-create-custom.yml
  .github/workflows/test-oblt-cli-cluster-create-serverless.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
  .github/workflows/test-oblt-cli-create-ccs.yml
  .github/workflows/test-oblt-cli-run.yml
  .github/workflows/test-oblt-cli-setup.yml
Labels: changelog:ci

#135 feat: migrate is-member-elastic-org
  .github/workflows/test-github-is-member-of.yml
  github/is-member-of/README.md
  github/is-member-of/action.yml
Labels: changelog:feature

#133 feat: support wait for maven central
  maven/await-artifact/README.md
  maven/await-artifact/action.yml
Labels: changelog:enhancement
