Repository elastic/oblt-actions, pull requests merged in 2024-10, with the labels that each got.

#140 feat: undeploy-my-kibana
  .github/workflows/test-oblt-cli-undeploy-my-kibana.yml
  oblt-cli/undeploy-my-kibana/README.md
  oblt-cli/undeploy-my-kibana/action.yml
Labels: changelog:enhancement

#143 feat: github/comment-reaction
  .github/workflows/test-github-comment-reaction.yml
  github/comment-reaction/README.md
  github/comment-reaction/action.yml
Labels: changelog:feature

#144 fix: id installation
  oblt-cli/undeploy-my-kibana/action.yml
Labels: changelog:fix

#147 docs: rename parameter in example
  oblt-cli/run/README.md
Labels: documentation, changelog:docs
