Repository elastic/oblt-actions, pull requests merged in 2024-06, with the labels that each got.

#18 feat(buildkite/download-artifact): support download artifacts from Buildkite
  .github/workflows/test-buildkite-download-artifact.yml
  .github/workflows/test-buildkite-run.yml
  buildkite/download-artifact/README.md
  buildkite/download-artifact/action.yml
  buildkite/download-artifact/download_artifacts.py
  buildkite/run/README.md
  buildkite/run/action.yml
  buildkite/run/run.sh
Labels: changelog:enhancement

#13 Add oblt-cli/cluster-create-serverless action
  .github/workflows/test-oblt-cli-cluster-create-serverless.yml
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-create-serverless/action.yml
Labels: changelog:feature

#14 Add oblt-cli/cluster-create-custom action
  .github/workflows/test-oblt-cli-cluster-create-custom-gitops.yml
  .github/workflows/test-oblt-cli-cluster-create-custom.yml
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-custom/action.yml
Labels: changelog:feature

#19 Fix dry-run input
  .github/workflows/test-oblt-cli-cluster-create-serverless.yml
Labels: changelog:ci

#21 Update docs with gh-action-readme cli
  buildkite/download-artifact/README.md
  buildkite/run/README.md
  docs/CONTRIBUTING.md
  git/setup/README.md
  git/setup/action.yml
  google/auth/README.md
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-custom/action.yml
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-credentials/README.md
  oblt-cli/cluster-name-validation/README.md
  oblt-cli/cluster-name-validation/action.yml
  oblt-cli/run/README.md
  oblt-cli/run/action.yml
  oblt-cli/setup/README.md
  oblt-cli/setup/action.yml
  slack/send/README.md
  updatecli/install/README.md
  updatecli/run-and-notify/README.md
  updatecli/run-and-notify/action.yml
  updatecli/run/README.md
Labels: changelog:docs

#20 Add oblt-cli/cluster-create-ccs action
  .github/workflows/test-oblt-cli-create-ccs.yml
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-ccs/action.yml
Labels: changelog:feature

#16 Add check-dependent-jobs action
  .github/workflows/no-test.yml
  .github/workflows/test-check-dependent-jobs.yml
  check-dependent-jobs/README.md
  check-dependent-jobs/action.yml
Labels: changelog:feature

#26 Refactor tests to use check-dependent-jobs action
  .github/workflows/test-buildkite-run.yml
  .github/workflows/test-oblt-cli-cluster-create-custom-gitops.yml
  .github/workflows/test-oblt-cli-cluster-create-custom.yml
  .github/workflows/test-oblt-cli-cluster-name-validation-cluster-info-file.yml
  .github/workflows/test-oblt-cli-cluster-name-validation-cluster-name.yml
  .github/workflows/test-oblt-cli-cluster-name-validation.yml
Labels: changelog:ci

#28 feat: slack/notify-result
  .github/workflows/test-slack-notify-result.yml
  slack/notify-result/README.md
  slack/notify-result/action.yml
Labels: changelog:feature

#31 Use action-readme pre-commit hook
  .ci/scripts/action-readme.sh
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  docs/CONTRIBUTING.md
Labels: changelog:ci

#32 Update action-readme pre-commit hook
  .pre-commit-config.yaml
Labels: changelog:ci

#30 feat(slack): support thread-timestamp
  .github/workflows/test-slack-send.yml
  slack/send/README.md
  slack/send/action.yml
Labels: changelog:enhancement

#33 Fix input description in slack/end
  slack/send/README.md
  slack/send/action.yml
Labels: changelog:docs

#29 feat(snapshoty): run
  .pre-commit-config.yaml
  snapshoty/run/.node-version
  snapshoty/run/README.md
  snapshoty/run/action.yml
  snapshoty/run/dist/index.js
  snapshoty/run/dist/licenses.txt
  snapshoty/run/index.js
  snapshoty/run/package-lock.json
  snapshoty/run/package.json
Labels: changelog:feature

#34 Add test status badge and test naming convention
  buildkite/download-artifact/README.md
  buildkite/run/README.md
  check-dependent-jobs/README.md
  docs/CONTRIBUTING.md
  git/setup/README.md
  google/auth/README.md
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-credentials/README.md
  oblt-cli/cluster-name-validation/README.md
  oblt-cli/run/README.md
  oblt-cli/setup/README.md
  slack/notify-result/README.md
  slack/send/README.md
Labels: changelog:docs

#36 Fix dry-run input in oblt-cli/create-cluster-ccs
  oblt-cli/cluster-create-ccs/action.yml
Labels: changelog:fix

#40 Remove google/auth usage in oblt-cli/create-* actions
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-serverless/README.md
Labels: changelog:docs

#38 Add dependabot config
  .github/dependabot.yml
Labels: changelog:dependencies

#37 Add oblt-cli/cluster-destroy action
  docs/CONTRIBUTING.md
  oblt-cli/cluster-destroy/README.md
  oblt-cli/cluster-destroy/action.yml
Labels: changelog:feature

#44 Use new glob pattern feature of gh-action-readme@v0.4.0
  .pre-commit-config.yaml
  buildkite/download-artifact/README.md
  buildkite/run/README.md
  check-dependent-jobs/README.md
  git/setup/README.md
  google/auth/README.md
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-credentials/README.md
  oblt-cli/cluster-name-validation/README.md
  oblt-cli/run/README.md
  oblt-cli/setup/README.md
  slack/notify-result/README.md
  slack/send/README.md
  snapshoty/run/README.md
  updatecli/install/README.md
  updatecli/run-and-notify/README.md
  updatecli/run/README.md
Labels: changelog:docs

#39 Fix oblt-cli/run action
  oblt-cli/run/action.yml
Labels: changelog:fix

#43 Add if: always() to test jobs with check-dependent-jobs steps
  .github/workflows/test-buildkite-run.yml
  .github/workflows/test-oblt-cli-cluster-create-custom.yml
  .github/workflows/test-oblt-cli-cluster-name-validation.yml
  .github/workflows/test-slack-notify-result.yml
Labels: changelog:ci

#45 oblt-cli/setup: Skip downloading if file already exists
  .github/workflows/test-oblt-cli-setup.yml
  oblt-cli/setup/download.sh
Labels: changelog:enhancement

#47 oblt-cli/run: Remove `--disable-banner` flag
  oblt-cli/run/action.yml
Labels: changelog:enhancement

#48 oblt-cli/run: Move global flags before command
  oblt-cli/run/action.yml
Labels: changelog:enhancement

#49 Add missing username input
  oblt-cli/cluster-destroy/README.md
  oblt-cli/cluster-destroy/action.yml
Labels: changelog:fix

#54 oblt-cli/setup: Pin oblt-cli version
  .github/workflows/no-test.yml
  .github/workflows/test-oblt-cli-setup.yml
  oblt-cli/setup/README.md
  oblt-cli/setup/action.yml
Labels: enhancement, changelog:enhancement

#61 Update dependabot.yml
  .github/dependabot.yml
Labels: changelog:chore

#63 Add aws/auth action
  .github/workflows/no-test.yml
  .github/workflows/test-aws-auth.yml
  aws/auth/README.md
  aws/auth/action.yml
Labels: changelog:feature

#67 fix(google/auth): honour the project-id input
  google/auth/action.yml
Labels: changelog:fix

#68 Add usage badges
  aws/auth/README.md
  buildkite/download-artifact/README.md
  buildkite/run/README.md
  check-dependent-jobs/README.md
  git/setup/README.md
  google/auth/README.md
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-custom/README.md
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-credentials/README.md
  oblt-cli/cluster-destroy/README.md
  oblt-cli/cluster-name-validation/README.md
  oblt-cli/run/README.md
  oblt-cli/setup/README.md
  slack/notify-result/README.md
  slack/send/README.md
  snapshoty/run/README.md
  updatecli/install/README.md
  updatecli/run-and-notify/README.md
  updatecli/run/README.md
Labels: changelog:docs

#69 oblt-cli/setup: Add version-file input
  .github/workflows/test-oblt-cli-setup.yml
  oblt-cli/setup/README.md
  oblt-cli/setup/action.yml
  oblt-cli/setup/download.sh
Labels: changelog:feature

#72 fix(google/auth): tabs are invalid
  google/auth/action.yml
Labels: changelog:fix
