Repository elastic/oblt-actions, pull requests merged in 2024-11, with the labels that each got.

#150 feat: replace apm-pipeline-library version-framework
  .github/workflows/test-version-framework.yml
  version-framework/README.md
  version-framework/action.yml
  version-framework/matrix.py
  version-framework/test-data/excluded.yml
  version-framework/test-data/frameworks.yml
  version-framework/test-data/versions.yml
Labels: changelog:feature

#149 feat: migrate is-pr-author-member-elastic-org@current
  .github/workflows/test-github-is-pr-author-member-of.yml
  github/is-pr-author-member-of/README.md
  github/is-pr-author-member-of/action.yml
Labels: changelog:enhancement

#153 feat: replace apm-pipeline-library kibana-docker-image
  .github/workflows/test-kibana-docker-image.yml
  kibana-docker-image/README.md
  kibana-docker-image/action.yml
  kibana-docker-image/build-and-push.sh
  kibana-docker-image/setup-vars.sh
Labels: changelog:feature

#157 github-actions: support manual runs and merge-queue
  .github/workflows/no-test.yml
  .github/workflows/pre-commit.yml
  .github/workflows/required-labels.yml
  .github/workflows/test-aws-auth.yml
  .github/workflows/test-buildkite-download-artifact.yml
  .github/workflows/test-buildkite-run.yml
  .github/workflows/test-check-dependent-jobs.yml
  .github/workflows/test-elastic-active-branches.yml
  .github/workflows/test-git-setup.yml
  .github/workflows/test-github-comment-reaction.yml
  .github/workflows/test-github-is-member-of.yml
  .github/workflows/test-github-is-pr-author-member-of.yml
  .github/workflows/test-google-auth.yml
  .github/workflows/test-kibana-docker-image.yml
  .github/workflows/test-maven-await-artifact.yml
  .github/workflows/test-oblt-cli-cluster-create-custom.yml
  .github/workflows/test-oblt-cli-cluster-create-serverless.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
  .github/workflows/test-oblt-cli-cluster-name-validation.yml
  .github/workflows/test-oblt-cli-create-ccs.yml
  .github/workflows/test-oblt-cli-deploy-my-kibana.yml
  .github/workflows/test-oblt-cli-run.yml
  .github/workflows/test-oblt-cli-setup.yml
  .github/workflows/test-oblt-cli-undeploy-my-kibana.yml
  .github/workflows/test-slack-notify-result.yml
  .github/workflows/test-slack-send.yml
  .github/workflows/test-updatecli-run.yml
  .github/workflows/test-version-framework.yml
Labels: changelog:ci

#161 ci: support for merge_queue
  .github/workflows/required-labels.yml
Labels: changelog:ci

#166 revert: use v2.68.0
  updatecli/install/action.yml
Labels: changelog:fix

#168 ci: avoid running often
  .github/workflows/test-oblt-cli-deploy-my-kibana.yml
Labels: changelog:ci

#171 aws/auth: Pass outputs from upstream action to this action
  .github/workflows/test-aws-auth.yml
  aws/auth/README.md
  aws/auth/action.yml
Labels: changelog:feature

#174 fix: slack send with multiline and special characters
  .github/workflows/test-slack-send.yml
  slack/send/action.yml
Labels: changelog:fix

#175 Remove invalid test again
  .github/workflows/test-aws-auth.yml
Labels: changelog:ci

#176 feat: use updatecli version in `updatecli/install`
  .ci/updatecli/updatecli.yml
  .github/workflows/test-updatecli-install.yml
  .github/workflows/test-updatecli-run.yml
  updatecli-compose.yaml
  updatecli/install/.default-updatecli-version
  updatecli/install/README.md
  updatecli/install/action.yml
Labels: changelog:enhancement
