Repository elastic/oblt-actions, pull requests merged in 2025-04, with the labels that each got.

#262 Add backport action
  .github/workflows/no-test.yml
  .github/workflows/test-github-backport-active.yml
  github/backport-active/README.md
  github/backport-active/action.yml
  github/backport-active/backport_script.py
Labels: changelog:feature, backport-active-8

#266 add UTs
  .github/workflows/test-github-backport-active.yml
  github/backport-active/test_backport_script.py
Labels: changelog:ci

#267 mergify: exclude 7.17 branch from backport-active-all
  github/backport-active/backport_script.py
  github/backport-active/test_backport_script.py
Labels: changelog:enhancement
