Repository elastic/oblt-actions, pull requests merged in 2025-02, with the labels that each got.

#228 chore: add license and notice
  LICENSE
  NOTICE
Labels: changelog:chore

#226 feat(create-ccs): support wait
  .github/workflows/test-oblt-cli-cluster-create-ccs.yml
  .github/workflows/test-oblt-cli-create-ccs.yml
  oblt-cli/cluster-create-ccs/README.md
  oblt-cli/cluster-create-ccs/action.yml
Labels: changelog:enhancement

#227 chore: change headers for the categories
  .github/release-drafter.yml
Labels: changelog:chore

#230 docs: add new secrets
  oblt-cli/cluster-credentials/README.md
Labels: changelog:docs

#234 fix: parsing th mergify PR
  mergify/labels-copier/copy.sh
Labels: changelog:fix

#241 fix: skip-docker-ubuntu was removed
  kibana-docker-image/build-and-push.sh
Labels: changelog:enhancement

#242 feat(serverless): support wait flag
  .github/workflows/test-oblt-cli-cluster-create-serverless.yml
  oblt-cli/cluster-create-serverless/README.md
  oblt-cli/cluster-create-serverless/action.yml
Labels: changelog:enhancement
