Repository elastic/oblt-actions, pull requests merged in 2025-09, with the labels that each got.

#339 feat: consider skipped job as success
  .github/workflows/test-check-dependent-jobs.yml
  check-dependent-jobs/README.md
  check-dependent-jobs/action.yml
Labels: changelog:enhancement

#345 feat(azure/login): first iteration
  .github/workflows/no-test.yml
  .github/workflows/test-azure-auth.yml
  azure/auth/README.md
  azure/auth/action.yml
Labels: enhancement, changelog:feature

#355 feat(changed-files): add changed output
  .github/workflows/no-test.yml
  .github/workflows/test-github-changed-files.yml
  .pre-commit-config.yaml
  github/changed-files/README.md
  github/changed-files/action.yml
  github/changed-files/dist/index.js
  github/changed-files/index.js
  github/changed-files/index.test.js
  github/changed-files/package.json
Labels: changelog:enhancement

#360 github user type detection fix for Copilot
  .github/workflows/no-test.yml
  .github/workflows/test-github-user-type.yml
  github/user-type/action.yml
Labels: changelog:fix
